### PR TITLE
Make sure no empty strings in server executable args

### LINKED ISSUE #468: Version 1.7.0 seems broken (for Ubuntu 20.04)
Hello developers,

Just a heads-up that it seems version 1.7.0 is broken in my environment, which is a freshly installed Ubuntu 20.04 VM.  The error message is something as follows:

```
Invalid argument `'

Usage: haskell-language-server-1.4.0-linux-8.10.7 [--version | 
                                                    --numeric-version | 
                                                    --probe-tools | 
                                                    --list-plugins | 
                                                    --print-cradle | 
                                                    [COMMAND | --lsp | 
                                                      FILES/DIRS...] [--cwd DIR]
                                                    [--shake-profiling DIR] 
                                                    [--test] [--example] 
                                                    [-d|--debug] 
                                                    [-l|--logfile LOGFILE] 
                                                    [-j NUM] 
                                                    [--project-ghc-version]]
  Used as a test bed to check your IDE Client will work
[Error - 5:27:41 PM] Connection to server got closed. Server will not be restarted.
```

It takes me an hour to figure this out since I feel I must miss something as this is just a very standard setup. Then I realized the plugin just released a new version, so there may be something wrong with the new version. I switched back to 1.6.1 and it's working again. I think this new release may confuse other users as well.

### PR DESCRIPTION
**Pull request by berberman**
Closes #468

It seems that `vscode-languageclient` will concatenate the arguments array into a string that our server won't accept if there are blank strings in the array.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -197,7 +197,7 @@ async function activateServerForFolder(context: ExtensionContext, uri: Uri, fold
   }
 
   let extraArgs: string = workspace.getConfiguration('haskell', uri).serverExtraArgs;
-  if (extraArgs !== null) {
+  if (extraArgs !== '') {
```
Comment (theqp) [inline src/extension.ts:200]: 1. Are you sure the deletion of the null check will not cause a null dereference at `extraArgs.split`?
2. What's the point of checking for empty strings if you filter them out at line 218?

**Review by jneira — APPROVED** [review]
many thanks for the quick fix merging

**Comment by jneira** [comment]
@berberman could you cut a minor  release with the fix, I will not be able to do it for some time
I think you will have the needed perms, only push the tag and make a release is needed to trigger CI publish
many thanks!
