### PR TITLE
Use local files on connection failure, closes #298

### LINKED ISSUE #298: Fails to start/activate without internet connection
### Steps to reproduce

1. Disable internet access (I disable wifi on my laptop)
2. Run command "Developer: Restart Extension Host"

### Result

Error popup saying *Couldn't get the latest haskell-language-server releases from GitHub: getaddrinfo ENOTFOUND api.github.com* and the extension is not started/activated.

### Expected

A warning popup is shown, notifying the user that the server could not be updated, but the current version of the extension is started/activated.

### PR DESCRIPTION
**Pull request by WorldSEnder**
Use already downloaded tools when fetching latest release metadata fails. This adds a small cache file in the `globalStoragePath` containing the last fetched information.

Does not currently implement the feature as requested in #281 as I'm not certain what exactly such a flag should do (pick one):
- Not download anything at all
- `"haskell.hlsUpdateBehavior": "keep-up-to-date"` Try to fetch latest release information, if that fails fall back to local cache (what is done with this PR automatically)
- `"haskell.hlsUpdateBehavior": "prompt"` Try to fetch latest release information, but not upgrade, even if it succeeds and instead display a prompt to update (probably sensible), still download artifacts for the proper ghc version, if necessary.
- `"haskell.hlsUpdateBehavior": "never-check"` Don't check for latest release information, and do not upgrade, but still download artifacts for missing ghc versions, if needed.

I would want to implement #281 in this PR if that behavior is cleared up for me :)

### CODE REVIEW

**Comment by WorldSEnder** [comment]
Ping @Meowcolm024 @runeksvendsen I would love to hear your feedback on this if you have time

**Comment by jneira** [comment]
The last one (display a prompt) seems to be more complete and user friendly, similar to how vscode itself does the updates.
I would not ask if no version is available cause it would make the extension fail to load any haskell content.
However second and third are complementary, right? Prompt if it is succesful and fall back to previous version automatically if it is not (with a specific waning).

**Comment by WorldSEnder** [comment]
The difference between the second and the third option is that the former is implemented, the latter would require some extra work - which I'm willing to put in, in any case.

**Comment by WorldSEnder** [comment]
Another point: I'm reading #272 and it seems the current code could use some validation of the json result returned from github, since it as written stores a potentially malformed result to disk. I first thought to maybe use a simple json schema to validate, but after researching the vscode environment, it seems one would have to include rather big dependencies to do that.

Something like [avj](https://www.npmjs.com/package/ajv) is quite a big dependency, a little bit smaller [io-ts](https://www.npmjs.com/package/io-ts), which at least doesn't have any transitive dependencies. Then there's two [very small](https://www.npmjs.com/package/type-safe-json-decoder) and [also small](https://www.npmjs.com/package/typed-validation) but probably not well maintained libraries. Honestly, I'd rather just write the logic directly inline. Any opinions on that?

**Comment by jneira** [comment]
I would say that inline would be better if the code is small enough, but I am not an expert in js/ts

**Comment by WorldSEnder** [comment]
Alright, this should now also address #272 (by doing validation on the data received from github) and #281 (by adding a configuration item that can be set to prompt before deciding to use a newer version)

File: src/hlsBinaries.ts [hunk 1]
```diff
@@ -3,12 +3,14 @@ import * as fs from 'fs';
...
-import { downloadFile, executableExists, userAgentHeader } from './utils';
+import { promisify } from 'util';
+import { env, ExtensionContext, ProgressLocation, Uri, window, workspace, WorkspaceFolder } from 'vscode';
+import { downloadFile, executableExists, httpsGetSilently } from './utils';
+import * as validate from './validation';
 
 /** GitHub API release */
 interface IRelease {
-  assets: [IAsset];
+  assets: IAsset[];
```
Comment (bubba) [inline src/hlsBinaries.ts:13]: Whoops nice catch. Spot the haskeller...

File: src/hlsBinaries.ts [hunk 2]
```diff
@@ -224,15 +289,8 @@ export async function downloadHaskellLanguageServer(
...
-  try {
-    await downloadFile(title, asset.browser_download_url, binaryDest);
-    return binaryDest;
-  } catch (e) {
-    if (e instanceof Error) {
-      window.showErrorMessage(e.message);
-    }
-    return null;
-  }
+  await downloadFile(title, asset.browser_download_url, binaryDest);
```
Comment (bubba) [inline src/hlsBinaries.ts:292]: Are the errors from `downloadFile` being caught or displayed anywhere? `downloadFile` can throw an error if the internet connection goes during the download etc which would be nice to display to the user

File: package.json [hunk 3]
```diff
@@ -151,6 +151,20 @@
...
+          "type": "string",
+          "enum": [
+            "keep-up-to-date",
+            "prompt"
+          ],
+          "enumDescriptions": [
+            "Always download the latest available version when it is published",
+            "Prompt before downloading a newer version"
+          ],
+          "default": true,
```
Comment (bubba) [inline package.json:166]: Should this be
```suggestion
          "default": 'keep-up-to-date',
```

Comment (WorldSEnder) [reply package.json:166]: Woops, good catch

File: src/hlsBinaries.ts (hunk 2 above)
Comment (WorldSEnder) [reply src/hlsBinaries.ts:292]: They should get caught here in [activateServerForFolder](https://github.com/haskell/vscode-haskell/blob/65a55b6c99b5c7824675a5b52914a7e22490deec/src/extension.ts#L161-L165). Let me try to intentionally fail the download real quick.

Comment (WorldSEnder) [reply src/hlsBinaries.ts:292]: An error shows up at that simply says `getaddrinfo EAI_AGAIN github.com`, probably want to improve the message a bit here.

Comment (WorldSEnder) [reply src/hlsBinaries.ts:301]: Now says something like `Failed to download <url of asset>: getaddrinfo EAI_AGAIN github.com`, which should be more clear.

**Review by bubba — APPROVED** [review]

**Comment by bubba** [comment]
Sounds like 5158096 also fixes #281, I'm happy with this design. This all LGTM, will quickly test it out locally

File: package.json [hunk 4]
```diff
@@ -151,6 +151,22 @@
           "type": "string",
           "default": "",
           "description": "Manually set a language server executable. Can be something on the $PATH or a path to an executable itself. Works with ~, ${HOME} and ${workspaceFolder}."
+        },
+        "haskell.hlsUpdateBehavior": {
```
Comment (bubba) [inline package.json:155]: One last nitpick sorry, the title gets rendered weirdly in VS Code like "Hls Update Behaviour", I think we can just assume the default is HLS and rename this
```suggestion
        "haskell.updateBehavior": {
```

**Review by bubba — APPROVED** [review]

**Comment by bubba** [comment]
Thanks for doing this, looks great
